### ISSUE TITLE
HPCurrC is not defined when using Rally Skills

### ISSUE THREAD

**Issue by kizo-also-known-as-kizuna** [missing-q/emblem20#4]
The error message I received was:
ReferenceError: HPCurrC is not defined
    at skillMain (apiscript.js:4064:44)
    at Skill (apiscript.js:4132:17)
    at apiscript.js:4136:9
    at eval (eval at <anonymous> (/home/node/d20-api-server/api.js:151:1), <anonymous>:65:16)
    at Object.publish (eval at <anonymous> (/home/node/d20-api-server/api.js:151:1), <anonymous>:70:8)
    at /home/node/d20-api-server/api.js:1634:12
    at /home/node/d20-api-server/node_modules/firebase/lib/firebase-node.js:93:560
    at hc (/home/node/d20-api-server/node_modules/firebase/lib/firebase-node.js:39:147)
    at Kd (/home/node/d20-api-server/node_modules/firebase/lib/firebase-node.js:93:546)
    at Id.Mb (/home/node/d20-api-server/node_modules/firebase/lib/firebase-node.js:93:489)
    at Zd.Ld.Mb (/home/node/d20-api-server/node_modules/firebase/lib/firebase-node.js:94:425)
    at /home/node/d20-api-server/node_modules/firebase/lib/firebase-node.js:111:400

**Comment by missing-q** [comment]
Fixed! It should be live on Roll20 as of the next update.

**Comment by kizo-also-known-as-kizuna** [comment]
Thank you very much
